export type JournalPost = {
  slug: string;
  category: string;
  title: string;
  date: string;
  read: string;
  excerpt: string;
  keywords: string[];
  // Article content rendered as ordered blocks
  body: Array<
    | { type: "h2"; text: string }
    | { type: "h3"; text: string }
    | { type: "p"; text: string }
    | { type: "quote"; text: string }
    | { type: "ul"; items: string[] }
  >;
};

export const posts: JournalPost[] = [
  {
    slug: "first-page-of-google-dubai",
    category: "SEO & Visibility",
    date: "Jun 2026",
    read: "8 min",
    title: "How to get your Dubai business on the first page of Google",
    excerpt:
      "Most businesses assume Google is a mystery. It isn't. It's a system — and once you understand how it works, getting to page one is less about luck and more about doing the right things consistently.",
    keywords: [
      "Dubai SEO",
      "first page of Google Dubai",
      "Google Business Profile Dubai",
      "local SEO Dubai",
      "rank on Google UAE",
      "Dubai web design",
    ],
    body: [
      { type: "p", text: "Here's a number worth sitting with: 92% of all Google searches never result in a click past the first page." },
      { type: "p", text: "Not page two. Not page three. Page one — and ideally, the top three results — is where virtually all the business happens. If your Dubai restaurant, clinic, law firm, or consultancy isn't showing up there, you're not in the conversation. Your competitor is." },
      { type: "p", text: "The frustrating thing is that most business owners know this. What they don't know is what to actually do about it. So let's fix that." },
      { type: "h2", text: "First, understand how Google actually thinks" },
      { type: "p", text: "Google's entire business model depends on giving people the most relevant, trustworthy answer to whatever they searched for. That's it. Every algorithm update, every ranking factor, every tweak — all of it serves that one goal." },
      { type: "p", text: "This means your job isn't to trick Google. It's to be the most genuinely helpful, credible, and trustworthy result for the searches your customers are making." },
      { type: "p", text: "Google ranks pages based on three core pillars: relevance, authority, and experience. Relevance is whether your page actually answers what someone searched for. Authority is whether other credible websites trust you enough to link to you. Experience is whether people who visit your site have a good time — fast loading, easy to navigate, works on mobile." },
      { type: "h2", text: "Step one: Know what your customers are actually searching" },
      { type: "p", text: "Before you change a word on your website, you need to know exactly what terms people type into Google when they're looking for what you offer. These are called keywords, and choosing the right ones is the foundation of everything." },
      { type: "p", text: "Use free tools like Google's Keyword Planner or Ubersuggest to find out what people are actually typing. And when you're doing this for a Dubai business, always think local." },
      { type: "p", text: "'Dentist' gets millions of searches. 'Dentist Dubai Marina' gets far fewer — but those fewer people are in your area, ready to book, and you have a much better chance of ranking for it. This is called a long-tail keyword, and for local businesses, it's where the real wins happen." },
      { type: "p", text: "Find 10 to 15 keywords that combine your service with your location. Examples: 'family law firm Dubai,' 'Italian restaurant Business Bay,' 'personal trainer JBR,' 'corporate tax advisor DIFC.' These are your targets." },
      { type: "quote", text: "The businesses that dominate Google locally aren't the biggest. They're the ones that understood what their customers were searching for and built their entire online presence around those specific terms." },
      { type: "h2", text: "Step two: Optimise every page on your site" },
      { type: "p", text: "Once you have your keywords, they need to appear in specific places on your website. This is called on-page SEO and it's the most direct thing you can do to improve your rankings." },
      { type: "p", text: "Every page on your site has a title tag — the text that appears as the clickable blue link in search results. Your title tag should include your primary keyword and your business name. 'Family Law Services in Dubai | Al Mansouri Legal' is far better than just 'About Us' or 'Home.'" },
      { type: "p", text: "Every page also has a meta description. Write it as an invitation. Tell them exactly what they'll find on the page and why they should choose you over the nine other results above and below yours." },
      { type: "p", text: "Your headlines, body copy, image file names, and image alt text should all contain natural, relevant references to your target keywords. Natural is the operative word — write for people, with keywords woven in intelligently." },
      { type: "h2", text: "Step three: Set up and optimise Google Business Profile" },
      { type: "p", text: "If you only do one thing after reading this article, do this. A fully optimised Google Business Profile is the single fastest way to appear in local search results — and it's completely free." },
      { type: "p", text: "Go to business.google.com and claim your listing if you haven't already. Then fill in every single field: business name, address, phone number, website, opening hours, service categories, service area, and a detailed business description that includes your keywords naturally." },
      { type: "p", text: "Upload high-quality photos. Businesses with photos receive 42% more direction requests and 35% more website clicks than those without." },
      { type: "p", text: "Ask every satisfied client for a Google review. A business with 50 reviews will almost always outrank one with 5, assuming everything else is equal." },
      { type: "h2", text: "Step four: Build authority through links" },
      { type: "p", text: "Authority in Google's eyes comes from other websites linking to yours. For a Dubai local business, the most valuable links come from local business directories, industry associations and chambers of commerce, local news publications, suppliers and partners, and guest posts on industry-relevant sites." },
      { type: "h2", text: "Step five: Make your website fast and mobile-friendly" },
      { type: "p", text: "Google explicitly uses page speed and mobile experience as ranking factors. Over 70% of searches in Dubai happen on mobile phones, so a site that doesn't work perfectly on a small screen is throwing away the majority of its potential traffic." },
      { type: "p", text: "Run your site through Google PageSpeed Insights. A score above 90 on mobile is your target. Below 60 and you have a real problem." },
      { type: "h2", text: "Step six: Create content that answers real questions" },
      { type: "p", text: "Google rewards websites that consistently publish genuinely useful content. A blog that answers the exact questions your potential customers are asking is one of the most powerful long-term SEO strategies available." },
      { type: "h2", text: "How long does it take?" },
      { type: "p", text: "For a local Dubai business in a moderately competitive niche, with a well-optimised website and a solid Google Business Profile, you should expect to see meaningful movement in rankings within 60–90 days. Reaching page one for your primary keywords typically takes 3–6 months of consistent effort." },
      { type: "quote", text: "SEO is the one marketing channel where the work you do today pays dividends for years. A Google Ad stops the moment you stop paying. A well-ranked website generates leads forever." },
      { type: "p", text: "Start with your Google Business Profile today. Add your target keywords to your page title tags this week. Ask your last five clients for a Google review. These three actions alone will put you ahead of the majority of your local competitors who are doing nothing." },
    ],
  },
  {
    slug: "website-cost-dubai-2025",
    category: "Web Design",
    date: "May 2026",
    read: "6 min",
    title: "How much does a website cost in Dubai in 2025 — the honest answer",
    excerpt:
      "Quotes ranging from AED 500 to AED 50,000 for what sounds like the same thing. Here's what's actually going on — and what you should actually pay.",
    keywords: [
      "website cost Dubai",
      "website price UAE",
      "Dubai web design pricing",
      "how much does a website cost in Dubai",
      "web design agency Dubai cost",
    ],
    body: [
      { type: "p", text: "Let's start with the number you're probably hoping for: a decent website for a Dubai small business costs between $997 and $5,000. That's the honest range for something professionally designed, mobile-optimised, SEO-ready, and built to generate leads." },
      { type: "p", text: "Below it, you're in DIY territory or offshore freelancer land. Above it, you're paying for either enterprise complexity or agency overhead. Understanding why is what this article is for." },
      { type: "h2", text: "Why the quotes you've received vary so wildly" },
      { type: "p", text: "You've probably had three conversations already. One person quoted you AED 1,500. Another quoted AED 15,000. And a third said 'it depends' and asked to schedule a call before saying anything at all." },
      { type: "p", text: "The variation isn't random. It reflects genuine differences in what's actually being delivered, who's delivering it, and what happens after the site goes live." },
      { type: "h3", text: "The AED 500–1,500 quote" },
      { type: "p", text: "This is usually someone on a freelancing platform, a student building a portfolio, or an offshore team in a cheaper market. You might get a site that looks acceptable in a screenshot. What you likely won't get: a site that loads quickly on mobile, ranks on Google, has proper SEO setup, or comes with any real support when something breaks." },
      { type: "h3", text: "The AED 20,000+ agency quote" },
      { type: "p", text: "Large established agencies have genuine overhead: account managers, project managers, designers, developers, QA teams, and office space in Business Bay or DIFC. For enterprise businesses with complex requirements, this is justified. For a restaurant, clinic, or professional services firm that needs a 5–10 page website, you are almost certainly overpaying." },
      { type: "h3", text: "The sweet spot" },
      { type: "p", text: "A specialised, productised web studio — one that has built a repeatable process for delivering high-quality websites quickly — can deliver everything a large agency would without the overhead markup. This is where you should be spending your money." },
      { type: "h2", text: "What your budget should actually include" },
      { type: "ul", items: [
        "Mobile-responsive design — tested on iPhone and Android, not just resized to fit.",
        "Page speed optimisation — your site should score above 90 on Google PageSpeed.",
        "On-page SEO — title tags, meta descriptions, header structure, image alt text.",
        "Google Analytics 4 — installed and tracking visitor behaviour from day one.",
        "Google Search Console — connected and your sitemap submitted.",
        "SSL certificate — non-negotiable for trust and SEO.",
        "Contact form — functional, mobile-friendly, sending emails correctly.",
        "Post-launch support — at minimum 30 days.",
      ]},
      { type: "quote", text: "A website without SEO setup is a shop with no sign above the door. It might be beautiful inside, but no one will ever find it." },
      { type: "h2", text: "The question nobody asks but everybody should" },
      { type: "p", text: "When you're comparing quotes, the most important question isn't 'how much does it cost?' It's 'how many leads do you expect this website to generate for my business?' If the person quoting you can't answer that — or doesn't even seem to have thought about it — that tells you something important about how they view their own work." },
      { type: "p", text: "A website that costs $2,500 and generates 20 new client enquiries per month is a $2,500 investment that pays for itself in week one. A website that costs $500 and generates nothing is $500 wasted." },
      { type: "h2", text: "Our pricing, clearly" },
      { type: "p", text: "At Saints Studios, we publish our prices because we believe opacity in this industry is a problem. Starter from $997, Growth $2,497, Premium $5,997. Every package is delivered in seven days or your first retainer month is free." },
    ],
  },
  {
    slug: "restaurant-invisible-online-dubai",
    category: "Restaurants & Food",
    date: "Apr 2026",
    read: "5 min",
    title: "Why your restaurant is invisible online — and how to fix it this week",
    excerpt:
      "You have a full dining room on Friday night. Your food is genuinely good. And yet, when someone searches 'good restaurant in your area,' your name doesn't appear. Here's why — and exactly what to do.",
    keywords: [
      "restaurant SEO Dubai",
      "Dubai restaurant marketing",
      "Google Business Profile restaurant",
      "restaurant website Dubai",
      "JBR restaurant SEO",
    ],
    body: [
      { type: "p", text: "The restaurant industry in Dubai is one of the most competitive in the world. The restaurants that consistently win the new customer battle aren't necessarily the ones with the best food. They're the ones who understood early that discovery happens online first — and built their presence accordingly." },
      { type: "h2", text: "Problem 1: Your Google Business Profile is incomplete or unclaimed" },
      { type: "p", text: "When someone searches 'Italian restaurant JBR' or 'best brunch Dubai Marina,' the results in the map section at the top of Google come from Google Business Profiles. Go to business.google.com today. Claim and fill every field: name, address, phone, website, opening hours, cuisine type, price range, and a detailed description. Upload at least 20 high-quality photos. Listings with photos get 35% more website clicks." },
      { type: "h2", text: "Problem 2: You have no website, or your website isn't indexed" },
      { type: "p", text: "Go to Google and type 'site:yourwebsite.com'. If nothing appears, your site isn't indexed. This needs fixing immediately. If you have no website at all, you're relying entirely on Google Business Profile, Zomato, and social media — competing with your hands tied behind your back." },
      { type: "quote", text: "Every reservation you take through a third-party platform is a reservation you paid commission on. Every reservation that comes through your own website is free." },
      { type: "h2", text: "Problem 3: Your website has no local SEO" },
      { type: "ul", items: [
        "Change your homepage title tag to '[Cuisine Type] Restaurant in [Area], Dubai | [Restaurant Name]'",
        "Write a meta description that includes cuisine, location, and a reason to click.",
        "Add your full address in text on both your homepage and contact page.",
        "Use your location and cuisine type naturally in your homepage copy.",
      ]},
      { type: "h2", text: "Problem 4: You have no reviews, or you're not responding to them" },
      { type: "p", text: "A restaurant with 200 reviews averaging 4.3 stars will almost always outperform one with 15 reviews averaging 4.7. Volume signals trustworthiness to both Google and to diners. Build a simple review request habit and respond to every review — good and bad." },
      { type: "h2", text: "Problem 5: Your social media links nowhere" },
      { type: "p", text: "Every person who sees your Instagram post and wants to make a reservation should be able to do so immediately. That means a working website link, a working reservation button, and ideally a WhatsApp link for instant communication." },
      { type: "h2", text: "The fix: what to do this week" },
      { type: "ul", items: [
        "Day 1: Claim and complete your Google Business Profile. Upload 20 photos.",
        "Day 2: Run 'site:yourwebsite.com' in Google. If nothing appears, contact your developer.",
        "Day 3: Update your homepage title tag and meta description.",
        "Day 4: WhatsApp your 10 most loyal regulars asking for a Google review.",
        "Day 5: Check your Instagram bio and link destinations.",
      ]},
    ],
  },
  {
    slug: "5-page-website-structure-that-converts",
    category: "Web Design",
    date: "Mar 2026",
    read: "7 min",
    title: "The 5-page website structure that generates the most leads",
    excerpt:
      "The websites that generate the most leads aren't the largest ones. They're the most focused ones. Five pages, each with a clear job.",
    keywords: [
      "website structure that converts",
      "small business website pages",
      "Dubai web design lead generation",
      "lead generating website",
      "5 page website",
    ],
    body: [
      { type: "p", text: "There's a common belief that a bigger website is a better website. More pages, more information, more trust. This sounds logical. It's wrong." },
      { type: "p", text: "The websites that generate the most leads for small and medium businesses are the most focused ones. Five pages, each with a clear job, each earning the right to send a visitor to the next one." },
      { type: "h2", text: "Page 1 — Homepage: The first 8 seconds" },
      { type: "p", text: "Your homepage has one job: convince the visitor they're in the right place and make them want to know more. The hero must answer three questions: What do you do? Who do you do it for? What should I do next?" },
      { type: "p", text: "Below the hero, you need social proof before more information. Logos, a review score, a number that demonstrates scale. Then the problem you solve. Then the solution. Then a strong, specific CTA — not 'contact us,' but 'Book a free 30-minute strategy call.'" },
      { type: "quote", text: "The homepage doesn't need to explain everything. It needs to make the visitor trust you enough to want to know more. Earn the scroll." },
      { type: "h2", text: "Page 2 — Services: Turn interest into intent" },
      { type: "p", text: "Every service needs to be presented as an outcome. Not 'Web Design' — instead: 'A website that ranks on Google, loads instantly, and converts visitors into enquiries — live in 7 days.' Each service description should answer: What is it? What does it do for my business? What's included? What does it cost?" },
      { type: "h2", text: "Page 3 — About: Make it human" },
      { type: "p", text: "Write your about page in first person. Tell a real story: why did you start this business? Put your face on the page. Include a clear explanation of who you work with and — this is powerful — who you don't." },
      { type: "h2", text: "Page 4 — Reviews or Case Studies: Prove it" },
      { type: "p", text: "Claims are cheap. Proof is expensive — and therefore infinitely more valuable. '+280% increase in monthly enquiries for a Dubai Marina restaurant, 90 days after launch' is worth fifty beautiful portfolio screenshots." },
      { type: "h2", text: "Page 5 — Contact: Remove every possible barrier" },
      { type: "p", text: "Minimum fields: Name, Email, Phone, one open question. Add a response time promise, a human face beside the form, and a direct WhatsApp link. When someone submits, confirm receipt with their name and tell them exactly when to expect a reply." },
      { type: "h2", text: "The thread that connects all five pages" },
      { type: "p", text: "Every page has one primary CTA. One. When you ask someone to do two things at once, they often do neither. The five-page structure isn't a limitation. It's a discipline." },
    ],
  },
  {
    slug: "core-web-vitals-explained",
    category: "SEO & Visibility",
    date: "Feb 2026",
    read: "6 min",
    title: "Core Web Vitals — what they are and why they affect ranking",
    excerpt:
      "Three specific measurements now directly influence where you appear in Google search results. Most business owners have never heard of them. Their competitors have.",
    keywords: [
      "Core Web Vitals",
      "LCP CLS INP",
      "PageSpeed Insights Dubai",
      "website speed SEO",
      "improve Core Web Vitals",
    ],
    body: [
      { type: "p", text: "Core Web Vitals is a set of three specific measurements Google uses to assess the real-world experience of visiting your website. Not theory. What it actually feels like to load your page on a real phone with a real internet connection." },
      { type: "h3", text: "Largest Contentful Paint (LCP) — loading" },
      { type: "p", text: "LCP measures how long it takes for the largest visible element on your page to fully load. Google wants this within 2.5 seconds. Anything over 4 seconds is a fail." },
      { type: "h3", text: "Interaction to Next Paint (INP) — interactivity" },
      { type: "p", text: "INP measures how quickly your site responds when a user does something. Target: under 200 milliseconds. INP issues usually come from too much JavaScript executing on page load." },
      { type: "h3", text: "Cumulative Layout Shift (CLS) — visual stability" },
      { type: "p", text: "CLS measures how much the page jumps around while loading. Google wants a CLS score below 0.1. Common causes: images without defined dimensions, web fonts loading and swapping, banner ads pushing content down." },
      { type: "quote", text: "Core Web Vitals is Google telling you clearly: fast, stable, responsive websites rank better." },
      { type: "h2", text: "The fixes that make the biggest difference" },
      { type: "ul", items: [
        "Convert your images to WebP format — typically 25–35% smaller than JPEG/PNG.",
        "Specify width and height on all images so the browser reserves space.",
        "Reduce third-party scripts — audit chat widgets, pixels, marketing tools.",
        "Upgrade your hosting from cheap shared hosting to managed cloud.",
        "Enable caching for returning visitors and common assets.",
      ]},
      { type: "p", text: "Run your five closest Dubai competitors through PageSpeed Insights right now. In most industries, you'll find that the majority are scoring below 70 on mobile. This is an opportunity." },
    ],
  },
  {
    slug: "whatsapp-button-on-your-website",
    category: "Lead Generation",
    date: "Jan 2026",
    read: "4 min",
    title: "Why WhatsApp should be on your website — and exactly how to set it up",
    excerpt:
      "In Dubai, WhatsApp is the preferred communication channel. If your website doesn't have a WhatsApp button, you are losing enquiries daily to businesses that do.",
    keywords: [
      "WhatsApp button website",
      "wa.me link Dubai",
      "WhatsApp business UAE",
      "website conversion Dubai",
      "WhatsApp lead generation",
    ],
    body: [
      { type: "p", text: "Over 90% of the UAE population uses WhatsApp — as their primary communication tool. For business enquiries, customer service, booking confirmations. In Dubai, it is completely normal to conduct the entire customer journey through WhatsApp." },
      { type: "p", text: "And yet the majority of Dubai business websites either don't have a WhatsApp button at all, or have one buried so deep in the contact page that it may as well not exist." },
      { type: "quote", text: "Your potential customers are one tap away from messaging you. The WhatsApp button is what makes that tap possible. Without it, they close the tab and message your competitor instead." },
      { type: "h2", text: "What kind of WhatsApp button should you use?" },
      { type: "p", text: "Personal WhatsApp — a direct link to your personal number — works for sole traders and small teams. The format is: wa.me/[your number with country code]. For a UAE number: wa.me/971501234567. No plus sign, no spaces." },
      { type: "p", text: "Add a pre-filled message: wa.me/971501234567?text=Hi%2C%20I%20found%20you%20via%20your%20website. This reduces the blank-page anxiety of starting a conversation." },
      { type: "p", text: "WhatsApp Business is the right choice for teams handling more than 20 enquiries per day or sharing an inbox. It supports automated greetings, away messages, and multiple agents via the API (WATI, Respond.io, Interakt)." },
      { type: "h2", text: "Where to place the button" },
      { type: "ul", items: [
        "Floating button — fixed to the bottom right of every page, the most-used placement.",
        "Navigation bar — visible from the moment the page loads, no scrolling required.",
        "Contact page — a dedicated 'Message us on WhatsApp' button alongside your contact form.",
        "Hero section — for businesses where instant communication is core (real estate, urgent services).",
      ]},
      { type: "h2", text: "One more thing: set an auto-reply" },
      { type: "p", text: "If you're using WhatsApp Business, set up an automatic greeting that fires when someone messages you for the first time. This confirms receipt, sets clear expectations for response time, and positions you as a professional, responsive business — before you've typed a single personal reply." },
      { type: "p", text: "The businesses that win in Dubai are the ones that meet their customers where their customers already are. In this city, that place is WhatsApp. Add it today." },
    ],
  },
];

export const getPost = (slug: string) => posts.find((p) => p.slug === slug);
